export const projects = [
  {
    id: 1,
    type: "web-design",
    industry: "tech",
    year: "2024",
    image: {
      src: "/images/ecommerce-platform.jpeg",
      alt: "E-commerce platform redesign",
      fallback: "/images/fallback-image.jpeg",
      height: "h-64",
    },
    hover: {
      title: "TechCorp Platform",
      subtitle: "Complete UX overhaul",
    },
    title: "E-commerce Platform Redesign",
    client: "TechCorp",
    description:
      "Complete UX overhaul resulting in 40% increase in conversion rates",
    tags: ["Web Design", "UX/UI"],
  },
  {
    id: 2,
    type: "branding",
    industry: "healthcare",
    year: "2024",
    image: {
      src: "/images/healthcare-brand-identity.jpeg",
      alt: "Healthcare brand identity",
      fallback: "/images/ecommerce-platform.jpeg",
      height: "h-80",
    },
    hover: {
      title: "MedCare Identity",
      subtitle: "Complete brand system",
    },
    title: "Healthcare Brand Identity",
    client: "MedCare Solutions",
    description:
      "Comprehensive brand identity for healthcare technology startup",
    tags: ["Branding", "Visual Identity"],
  },
  {
    id: 3,
    type: "ux-ui",
    industry: "finance",
    year: "2024",
    image: {
      src: "/images/healthcare-brand-identity.jpeg",
      alt: "FinTech mobile app",
      fallback: "/images/healthcare-brand-identity.jpeg",
      height: "h-64",
    },
    hover: {
      title: "FinTech App",
      subtitle: "Mobile banking solution",
    },
    title: "FinTech Mobile App",
    client: "StartupXYZ",
    description: "User-centered design for complex financial workflows",
    tags: ["UX/UI", "Mobile Design"],
  },
  {
    id: 4,
    type: "development",
    industry: "ecommerce",
    year: "2023",
    image: {
      src: "/images/analytics-dashboard.jpeg",
      alt: "E-commerce dashboard",
      fallback: "/images/healthcare-brand-identity.jpeg",
      height: "h-72",
    },
    hover: {
      title: "Analytics Dashboard",
      subtitle: "Data visualization platform",
    },
    title: "Analytics Dashboard",
    client: "DataCorp",
    description: "Complex data visualization made intuitive and actionable",
    tags: ["Development", "Data Viz"],
  },
  {
    id: 5,
    type: "web-design",
    industry: "nonprofit",
    year: "2023",
    image: {
      src: "/images/typography-guide.jpeg",
      alt: "Non-profit website",
      fallback: "/images/analytics-dashboard.jpeg",
      height: "h-64",
    },
    hover: {
      title: "Non-profit Site",
      subtitle: "Mission-driven design",
    },
    title: "Non-profit Website",
    client: "Hope Foundation",
    description: "Accessible design focused on storytelling and donations",
    tags: ["Web Design", "Accessibility"],
  },
  {
    id: 6,
    type: "branding",
    industry: "education",
    year: "2023",
    image: {
      src: "/images/typography-guide.jpeg",
      alt: "Education platform branding",
      fallback: "/images/typography-guide.jpeg",
      height: "h-80",
    },
    hover: {
      title: "EduTech Brand",
      subtitle: "Learning platform identity",
    },
    title: "Education Platform Branding",
    client: "LearnTech",
    description: "Brand identity for innovative online learning platform",
    tags: ["Branding", "Education"],
  },
  {
    id: 7,
    type: "ux-ui",
    industry: "tech",
    year: "2022",
    image: {
      src: "/images/design-trends-showcase.jpeg",
      alt: "SaaS platform design",
      fallback: "/images/typography-guide.jpeg",
      height: "h-64",
    },
    hover: {
      title: "SaaS Platform",
      subtitle: "Enterprise solution",
    },
    title: "SaaS Platform Design",
    client: "CloudTech",
    description: "Enterprise-grade platform with intuitive user experience",
    tags: ["UX/UI", "Enterprise"],
  },
  {
    id: 8,
    type: "development",
    industry: "healthcare",
    year: "2022",
    image: {
      src: "/images/design-process-hero.jpeg",
      alt: "Healthcare app development",
      fallback: "/images/design-trends-showcase.jpeg",
      height: "h-72",
    },
    hover: {
      title: "HealthTech App",
      subtitle: "Patient management system",
    },
    title: "Healthcare Management App",
    client: "HealthTech Solutions",
    description: "Secure patient management system with HIPAA compliance",
    tags: ["Development", "Healthcare"],
  },
];
